package com.stocktrack.backend.audit.enums;

public enum AuditAction {
    USER_LOGIN,
    USER_LOGOUT,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_PASSWORD_CHANGED,
    USER_ROLES_CHANGED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    STOCK_ADJUSTED,
    TRANSACTION_CREATED,
    SUPPLIER_CREATED,
    SUPPLIER_UPDATED,
    SUPPLIER_DELETED,
    BACKUP_CREATED,
    SYSTEM_ERROR
}
